In [2]:
import cv2

In [4]:
my_img = cv2.imread("2-smallgray.png",0)
print(my_img)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [5]:
my_img = cv2.imread("2-smallgray.png",1)
print(my_img)

[[[187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]]

 [[198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]]

 [[209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]]]


In [6]:
cv2.imwrite("2-createdimage.png",my_img)

True

In [8]:
my_img = cv2.imread("2-smallgray.png",0)
print(my_img)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [10]:
my_img[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [14]:
for i in my_img:
    print(i)


[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [17]:
for i in my_img.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [24]:
for i in my_img.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [25]:
print(my_img)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [26]:
# stacking arrays
import numpy
img_horisplit=numpy.hstack((my_img,my_img,my_img))
print(img_horisplit)

[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]]


In [28]:
img_vertisplit=numpy.vstack((my_img,my_img,my_img))
print(img_vertisplit)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [34]:
# splitting arrays
split1=numpy.hsplit(img_vertisplit,5)
print(split1)

[array([[187],
       [198],
       [209],
       [187],
       [198],
       [209],
       [187],
       [198],
       [209]], dtype=uint8), array([[158],
       [125],
       [134],
       [158],
       [125],
       [134],
       [158],
       [125],
       [134]], dtype=uint8), array([[104],
       [255],
       [255],
       [104],
       [255],
       [255],
       [104],
       [255],
       [255]], dtype=uint8), array([[121],
       [255],
       [ 97],
       [121],
       [255],
       [ 97],
       [121],
       [255],
       [ 97]], dtype=uint8), array([[143],
       [147],
       [182],
       [143],
       [147],
       [182],
       [143],
       [147],
       [182]], dtype=uint8)]


In [36]:
split2=numpy.vsplit(img_vertisplit,3)
print(split2)

[array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8), array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8), array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)]


In [38]:
type(split2)

list

In [39]:
split2[0]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)